//13 de Agosto del 2021
//Miguel Angel Hernandez Orbe
//Programa que permite administrar el inventario y ventas de una tienda
//Practica #1 libre
package Tienda;


/**
 *
 * @author MATIAS
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        OperacionesEnUnaTienda Ope=new OperacionesEnUnaTienda();
        this.setLocationRelativeTo(null);
        Ope.ImagenInicio(EtiMargen, BotonInventario, BotonVender);
        Ope.ArchivoInventario();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiVender = new javax.swing.JLabel();
        EtiInventario = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        BotonVender = new javax.swing.JButton();
        BotonInventario = new javax.swing.JButton();
        EtiMargen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtiVender.setText("Vender");
        getContentPane().add(EtiVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        EtiInventario.setText("Inventario");
        getContentPane().add(EtiInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 275, -1, -1));

        BotonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVenderActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 200));

        BotonInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonInventarioMouseClicked(evt);
            }
        });
        BotonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 200));

        EtiMargen.setBackground(new java.awt.Color(255, 255, 255));
        EtiMargen.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(EtiMargen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInventarioMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Inventario().setVisible(true);
    }//GEN-LAST:event_BotonInventarioMouseClicked

    private void BotonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVenderActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Vender().setVisible(true);
    }//GEN-LAST:event_BotonVenderActionPerformed

    private void BotonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInventarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inventario().setVisible(true);
    }//GEN-LAST:event_BotonInventarioActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInventario;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonVender;
    private javax.swing.JLabel EtiInventario;
    private javax.swing.JLabel EtiMargen;
    private javax.swing.JLabel EtiVender;
    // End of variables declaration//GEN-END:variables
}
