//13 de Agosto del 2021
//Miguel Angel Hernandez Orbe
//Programa que permite administrar el inventario y ventas de una tienda
//Practica #1 libre
package Tienda;


/**
 *
 * @author MATIAS
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inventario() {
        initComponents();
        OperacionesEnUnaTienda Ope=new OperacionesEnUnaTienda();
        this.setLocationRelativeTo(null);
        Ope.ImagenInventario(EtiMargen, BotonRevisar, BotonAbastecer);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiAbastecer = new javax.swing.JLabel();
        EtiRevisar = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JButton();
        BotonAbastecer = new javax.swing.JButton();
        BotonRevisar = new javax.swing.JButton();
        EtiMargen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtiAbastecer.setText("Abastecer");
        getContentPane().add(EtiAbastecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        EtiRevisar.setText("Revisar");
        getContentPane().add(EtiRevisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        BotonInicio.setText("Inicio");
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        BotonAbastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbastecerActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAbastecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 200));

        BotonRevisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRevisarMouseClicked(evt);
            }
        });
        BotonRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRevisarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRevisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 200));

        EtiMargen.setBackground(new java.awt.Color(255, 255, 255));
        EtiMargen.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(EtiMargen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRevisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRevisarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Revisar().setVisible(true);
    }//GEN-LAST:event_BotonRevisarMouseClicked

    private void BotonAbastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbastecerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AbastecerInventario().setVisible(true);
    }//GEN-LAST:event_BotonAbastecerActionPerformed

    private void BotonRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRevisarActionPerformed
        // TODO add your handling code here:
       this.dispose();
        new Revisar().setVisible(true);
    }//GEN-LAST:event_BotonRevisarActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_BotonInicioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbastecer;
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonRevisar;
    private javax.swing.JLabel EtiAbastecer;
    private javax.swing.JLabel EtiMargen;
    private javax.swing.JLabel EtiRevisar;
    // End of variables declaration//GEN-END:variables
}
